<script type="text/javascript">
//<![CDATA[
$j(document).ready(function () {
    if ($j('.product-custom-option[type="file"]').length > 0) {
        Translator.add('The file is too large to be processed by the web server. Please, try to resize it and try again.', '<?php echo $this->__('The file is too large to be processed by the web server. Please, try to resize it and try again.') ?>');
        const oagUploadProgressBarCheckoutUrl = '<?php echo $this->getUploadProgressBarAddToCartUrl(); ?>';
        OagUploadProgressBar.init(oagUploadProgressBarCheckoutUrl);
    }
});
//]]>
</script>